local M = {}

function M.get(c, opts)
  local highlights = {}

  -- nvim-treesitter
  highlights.TSStrong = { bold = true }
  highlights.TSEmphasis = { italic = true }
  highlights.TSUnderline = { underline = true }
  highlights.TSNote = { fg = c.bg0[1], bg = c.green[1], bold = true }
  highlights.TSWarning = { fg = c.bg0[1], bg = c.yellow[1], bold = true }
  highlights.TSDanger = { fg = c.bg0[1], bg = c.red[1], bold = true }
  highlights.TSAnnotation = 'Purple'
  highlights.TSAttribute = 'Purple'
  highlights.TSBoolean = 'Yellow'
  highlights.TSCharacter = 'Aqua'
  highlights.TSCharacterSpecial = 'SpecialChar'
  highlights.TSComment = 'Comment'
  highlights.TSConditional = 'Red'
  highlights.TSConstBuiltin = 'OrangeItalic'
  highlights.TSConstMacro = 'RedItalic'
  highlights.TSConstant = 'Orange'
  highlights.TSConstructor = 'OrangeBold'
  highlights.TSDebug = 'Debug'
  highlights.TSDefine = 'Define'
  highlights.TSEnvironment = 'Macro'
  highlights.TSEnvironmentName = 'Type'
  highlights.TSError = 'Error'
  highlights.TSException = 'Red'
  highlights.TSField = 'Grey'
  highlights.TSFloat = 'Yellow'
  highlights.TSFuncBuiltin = 'OrangeBold'
  highlights.TSFuncMacro = 'OrangeBold'
  highlights.TSFunction = 'Orange'
  highlights.TSFunctionCall = 'Orange'
  highlights.TSInclude = 'Red'
  highlights.TSKeyword = 'Red'
  highlights.TSKeywordFunction = 'Red'
  highlights.TSKeywordOperator = 'Orange'
  highlights.TSKeywordReturn = 'Red'
  highlights.TSLabel = 'Orange'
  highlights.TSLiteral = 'String'
  highlights.TSMath = 'Blue'
  highlights.TSMethod = 'Orange'
  highlights.TSMethodCall = 'Orange'
  highlights.TSNamespace = 'YellowItalic'
  highlights.TSNone = 'Fg'
  highlights.TSNumber = 'Yellow'
  highlights.TSOperator = 'Grey'
  highlights.TSParameter = 'Fg'
  highlights.TSParameterReference = 'Fg'
  highlights.TSPreProc = 'PreProc'
  highlights.TSProperty = 'Blue'
  highlights.TSPunctBracket = 'Grey'
  highlights.TSPunctDelimiter = 'Grey'
  highlights.TSPunctSpecial = 'Grey'
  highlights.TSRepeat = 'Red'
  highlights.TSStorageClass = 'Orange'
  highlights.TSStorageClassLifetime = 'Orange'
  highlights.TSStrike = 'Grey'
  highlights.TSString = 'Yellow'
  highlights.TSStringEscape = 'Orange'
  highlights.TSStringRegex = 'Orange'
  highlights.TSStringSpecial = 'SpecialChar'
  highlights.TSSymbol = 'Fg'
  highlights.TSTag = 'Orange'
  highlights.TSTagAttribute = 'Green'
  highlights.TSTagDelimiter = 'Green'
  highlights.TSText = 'Green'
  highlights.TSTextReference = 'Constant'
  highlights.TSTitle = 'Title'
  highlights.TSTodo = 'Todo'
  highlights.TSType = 'YellowItalic'
  highlights.TSTypeBuiltin = 'YellowItalic'
  highlights.TSTypeDefinition = 'YellowItalic'
  highlights.TSTypeQualifier = 'Orange'
  highlights.TSURI = { fg = c.blue[1], underline = true }
  highlights.TSVariable = 'Fg'
  highlights.TSVariableBuiltin = 'PurpleItalic'

  highlights['@annotation'] = 'TSAnnotation'
  highlights['@attribute'] = 'TSAttribute'
  highlights['@boolean'] = 'TSBoolean'
  highlights['@character'] = 'TSCharacter'
  highlights['@character.special'] = 'TSCharacterSpecial'
  highlights['@comment'] = 'TSComment'
  highlights['@comment.error'] = 'TSDanger'
  highlights['@comment.note'] = 'TSNote'
  highlights['@comment.todo'] = 'TSTodo'
  highlights['@comment.warning'] = 'TSWarning'
  highlights['@conceal'] = 'Grey'
  highlights['@conditional'] = 'TSConditional'
  highlights['@constant'] = 'TSConstant'
  highlights['@constant.builtin'] = 'TSConstBuiltin'
  highlights['@constant.macro'] = 'TSConstMacro'
  highlights['@constructor'] = 'TSConstructor'
  highlights['@debug'] = 'TSDebug'
  highlights['@define'] = 'TSDefine'
  highlights['@diff.delta'] = 'diffChanged'
  highlights['@diff.minus'] = 'diffRemoved'
  highlights['@diff.plus'] = 'diffAdded'
  highlights['@error'] = 'TSError'
  highlights['@exception'] = 'TSException'
  highlights['@field'] = { fg = c.grey2[1] }
  highlights['@float'] = 'TSFloat'
  highlights['@function'] = 'TSFunction'
  highlights['@function.builtin'] = 'TSFuncBuiltin'
  highlights['@function.call'] = 'TSFunctionCall'
  highlights['@function.macro'] = 'TSFuncMacro'
  highlights['@function.method'] = 'TSMethod'
  highlights['@function.method.call'] = 'TSMethodCall'
  highlights['@include'] = 'TSInclude'
  highlights['@keyword'] = 'TSKeyword'
  highlights['@keyword.conditional'] = 'TSConditional'
  highlights['@keyword.debug'] = 'TSDebug'
  highlights['@keyword.directive'] = 'TSPreProc'
  highlights['@keyword.directive.define'] = 'TSDefine'
  highlights['@keyword.exception'] = 'TSException'
  highlights['@keyword.function'] = 'TSKeywordFunction'
  highlights['@keyword.import'] = 'TSInclude'
  highlights['@keyword.operator'] = 'TSKeywordOperator'
  highlights['@keyword.repeat'] = 'TSRepeat'
  highlights['@keyword.return'] = 'TSKeywordReturn'
  highlights['@keyword.storage'] = 'TSStorageClass'
  highlights['@label'] = 'TSLabel'
  highlights['@markup.emphasis'] = 'TSEmphasis'
  highlights['@markup.environment'] = 'TSEnvironment'
  highlights['@markup.environment.name'] = 'TSEnvironmentName'
  highlights['@markup.heading'] = 'TSTitle'
  highlights['@markup.link'] = 'TSTextReference'
  highlights['@markup.link.label'] = 'TSStringSpecial'
  highlights['@markup.link.url'] = 'TSURI'
  highlights['@markup.list'] = 'TSPunctSpecial'
  highlights['@markup.list.checked'] = 'Green'
  highlights['@markup.list.unchecked'] = 'Ignore'
  highlights['@markup.math'] = 'TSMath'
  highlights['@markup.note'] = 'TSNote'
  highlights['@markup.quote'] = 'Grey'
  highlights['@markup.raw'] = 'TSLiteral'
  highlights['@markup.strike'] = 'TSStrike'
  highlights['@markup.strong'] = 'TSStrong'
  highlights['@markup.underline'] = 'TSUnderline'
  highlights['@math'] = 'TSMath'
  highlights['@method'] = 'TSMethod'
  highlights['@method.call'] = 'TSMethodCall'
  highlights['@module'] = 'TSNamespace'
  highlights['@namespace'] = 'TSNamespace'
  highlights['@none'] = 'TSNone'
  highlights['@number'] = 'TSNumber'
  highlights['@number.float'] = 'TSFloat'
  highlights['@operator'] = { fg = c.grey2[1] }
  highlights['@parameter'] = 'TSParameter'
  highlights['@parameter.reference'] = 'TSParameterReference'
  highlights['@preproc'] = 'TSPreProc'
  highlights['@property'] = 'TSProperty'
  highlights['@punctuation.bracket'] = { fg = c.grey1[1] }
  highlights['@punctuation.delimiter'] = { fg = c.grey1[1] }
  highlights['@punctuation.special'] = { fg = c.grey2[1] }
  highlights['@repeat'] = 'TSRepeat'
  highlights['@storageclass'] = 'TSStorageClass'
  highlights['@storageclass.lifetime'] = 'TSStorageClassLifetime'
  highlights['@strike'] = 'TSStrike'
  highlights['@string'] = 'TSString'
  highlights['@string.escape'] = 'TSStringEscape'
  highlights['@string.regex'] = 'TSStringRegex'
  highlights['@string.regexp'] = 'TSStringRegex'
  highlights['@string.special'] = 'TSStringSpecial'
  highlights['@string.special.symbol'] = 'TSSymbol'
  highlights['@string.special.uri'] = 'TSURI'
  highlights['@symbol'] = 'TSSymbol'
  highlights['@tag'] = 'TSTag'
  highlights['@tag.attribute'] = 'TSTagAttribute'
  highlights['@tag.delimiter'] = 'TSTagDelimiter'
  highlights['@text'] = 'TSText'
  highlights['@text.danger'] = 'TSDanger'
  highlights['@text.diff.add'] = 'diffAdded'
  highlights['@text.diff.delete'] = 'diffRemoved'
  highlights['@text.emphasis'] = 'TSEmphasis'
  highlights['@text.environment'] = 'TSEnvironment'
  highlights['@text.environment.name'] = 'TSEnvironmentName'
  highlights['@text.literal'] = 'TSLiteral'
  highlights['@text.math'] = 'TSMath'
  highlights['@text.note'] = 'TSNote'
  highlights['@text.reference'] = 'TSTextReference'
  highlights['@text.strike'] = 'TSStrike'
  highlights['@text.strong'] = 'TSStrong'
  highlights['@text.title'] = 'TSTitle'
  highlights['@text.todo'] = 'TSTodo'
  highlights['@text.todo.checked'] = 'Green'
  highlights['@text.todo.unchecked'] = 'Ignore'
  highlights['@text.underline'] = 'TSUnderline'
  highlights['@text.uri'] = 'TSURI'
  highlights['@text.warning'] = 'TSWarning'
  highlights['@todo'] = 'TSTodo'
  highlights['@type'] = 'TSType'
  highlights['@type.builtin'] = 'TSTypeBuiltin'
  highlights['@type.definition'] = 'TSTypeDefinition'
  highlights['@type.qualifier'] = 'TSTypeQualifier'
  highlights['@uri'] = 'TSURI'
  highlights['@variable'] = { fg = c.fg1[1] }
  highlights['@variable.builtin'] = 'TSVariableBuiltin'
  highlights['@variable.member'] = { fg = c.grey2[1] }
  highlights['@variable.parameter'] = 'TSParameter'

  highlights['@lsp.type.class'] = 'TSType'
  highlights['@lsp.type.comment'] = 'TSComment'
  highlights['@lsp.type.decorator'] = 'TSFunction'
  highlights['@lsp.type.enum'] = 'TSType'
  highlights['@lsp.type.enumMember'] = 'TSProperty'
  highlights['@lsp.type.events'] = 'TSLabel'
  highlights['@lsp.type.function'] = 'TSFunction'
  highlights['@lsp.type.interface'] = 'TSType'
  highlights['@lsp.type.keyword'] = 'TSKeyword'
  highlights['@lsp.type.macro'] = 'TSConstMacro'
  highlights['@lsp.type.method'] = 'TSMethod'
  highlights['@lsp.type.modifier'] = 'TSTypeQualifier'
  highlights['@lsp.type.namespace'] = 'TSNamespace'
  highlights['@lsp.type.number'] = 'TSNumber'
  highlights['@lsp.type.operator'] = 'TSOperator'
  highlights['@lsp.type.parameter'] = 'TSParameter'
  highlights['@lsp.type.property'] = 'TSProperty'
  highlights['@lsp.type.regexp'] = 'TSStringRegex'
  highlights['@lsp.type.string'] = 'TSString'
  highlights['@lsp.type.struct'] = 'TSType'
  highlights['@lsp.type.type'] = 'TSType'
  highlights['@lsp.type.typeParameter'] = 'TSTypeDefinition'
  highlights['@lsp.type.variable'] = 'TSVariable'

  highlights.TSModuleInfoGood = 'Green'
  highlights.TSModuleInfoBad = 'Red'

  -- Parameters: fg1 warm off-white, italic when enabled
  highlights['@parameter']                 = { fg = c.fg1[1], italic = opts.enable_italic }
  highlights['@variable.parameter']        = { fg = c.fg1[1], italic = opts.enable_italic }
  highlights['@lsp.type.parameter']        = { fg = c.fg1[1], italic = opts.enable_italic }
  highlights['@lsp.type.parameter.lua']    = { fg = c.fg1[1], italic = opts.enable_italic }
  highlights['@lsp.type.parameter.python'] = { fg = c.fg0[1], italic = true }

  return highlights
end

return M
